defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: desoroscopo_development

test:
  <<: *defaults
  database: desoroscopo_test
cucumber:
    <<: *defaults
    database: desoroscopo_cucumber

# set these environment variables on your prod server
production:
  <<: *defaults
  <% unless ENV['MONGOID_HOST'].nil? %>
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  <% end %> 
  database: desoroscopo_production